#$(document).ready ->
#  $('.nav-tabs > li').click ->
#    console.log('lol')
#    $('.nav-tabs > li').each (i) ->
#      if $(this).hasClass('active')
#        $(this).removeClass 'active'
#      else
#
#      return
#    $(this).addClass 'active'
#    return
#  return

# ---
# generated by js2coffee 2.2.0